app1/urls.py
from django.urls import path
from .import views
app_name='app1'
urlpatterns=[
    path('',views.index,name='index'),
    path('signup',views.signup,name='signup'),
    path('login',views.login,name='login'),
    path('home/<int:id>',views.home,name='home'),
    path('gallery',views.gallery,name='gallery'),
    path('details/<int:id>',views.details,name='details'),
    path('update/<int:id>',views.update,name='update'),
    path('changepassword/<int:id>',views.changepassword,name='changepassword'),
    path('logouts',views.logouts,name='logouts'),
]

assignment1/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import static,staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('app1.urls')),
]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

app1/models.py
from django.db import models

# Create your models here.
class Signup(models.Model):
    Name=models.CharField(max_length=20)
    Age=models.IntegerField()
    Email=models.EmailField()
    Password=models.CharField(max_length=9)


class Image(models.Model):
    Photo=models.ImageField(upload_to='media/',null=True,blank=True)

class Signup1(models.Model):
    Name=models.CharField(max_length=20)
    Age=models.IntegerField()
    Photo=models.ImageField(upload_to='media/',null=True,blank=True)
    Email=models.EmailField()
    Password=models.CharField(max_length=9)
    

class Image1(models.Model):
    Name=models.CharField(max_length=20)
    Brand=models.CharField(max_length=20)
    Model=models.CharField(max_length=20)
    year=models.CharField(max_length=20)
    Photo=models.ImageField(upload_to='media/',null=True,blank=True)

app1/forms.py
from django import forms
from .models import Signup1,Image

class SignupForm(forms.ModelForm):
    Password=forms.CharField(widget=forms.PasswordInput,max_length=9,min_length=3)
    ConfirmPassword=forms.CharField(widget=forms.PasswordInput,max_length=9,min_length=3)
    class Meta():
        model=Signup1
        fields='__all__'

class LoginForm(forms.ModelForm):
    Password=forms.CharField(widget=forms.PasswordInput,max_length=9,min_length=3)
    class Meta():
        model=Signup1
        fields=('Email','Password')

class ImageUploadForm(forms.ModelForm):
    class Meta():
        model=Image
        fields='__all__'

class UpdateForm(forms.ModelForm):
    class Meta():
        model=Signup1
        fields=('Name','Age','Email','Photo')

class ChangePasswordForm(forms.Form):
    OldPassword=forms.CharField(widget=forms.PasswordInput,max_length=9,min_length=3)
    NewPassword=forms.CharField(widget=forms.PasswordInput,max_length=9,min_length=3)
    ConfirmPassword=forms.CharField(widget=forms.PasswordInput,max_length=9,min_length=3)
    

app1/views.py
from django.shortcuts import render,redirect
from django.contrib.auth import logout
from django.contrib import messages
from .forms import SignupForm,LoginForm,ImageUploadForm,UpdateForm,ChangePasswordForm
from .models import Signup1,Image1
# Create your views here.
def index(request):
    return render(request, 'index.html')

def signup(request):
    if request.method=='POST':
        form=SignupForm(request.POST or none,request.FILES or None)
        if form.is_valid():
            name=form.cleaned_data['Name']
            age=form.cleaned_data['Age']
            email=form.cleaned_data['Email']
            password=form.cleaned_data['Password']
            photo=form.cleaned_data['Photo']
            confirm=form.cleaned_data['ConfirmPassword']

            user=Signup1.objects.filter(Email=email).exists()

            if user:
                messages.warning(request, "Email Already Exixts")
                return redirect('/signup')
            elif password!=confirm:
                messages.warning(request, "Mismatch")
                return redirect('/signup')
            else:
                tab=Signup1(Name=name,Age=age,Photo=photo,Email=email,Password=password)
                tab.save()
                messages.success(request, "Signup Succesfully")
                return redirect('/')
    else:
        form=SignupForm()
    return render(request, 'signup.html',{'form':form})

def login(request):
    if request.method=='POST':
        form=LoginForm(request.POST)
        if form.is_valid():
            email=form.cleaned_data['Email']
            password=form.cleaned_data['Password']
            
            try:
                user=Signup1.objects.get(Email=email)

                if not user:
                    messages.warning(request, "Email doesnot Exists")
                    return redirect('/login')
                elif password!=user.Password:
                    messages.warning(request, "Incorrect")
                    return redirect('/login')
                else:
                    messages.success(request, "Login succesfully")
                    return redirect('/home/%s' % user.id)
            except:
                messages.warning(request, "Email or Password incorrect ")
                return redirect('/signup')
    else:
        form=LoginForm()
    return render(request,'login.html',{'form':form})


def home(request,id):
    data=Signup1.objects.get(id=id)
    return render(request, 'home.html',{'data':data})


def gallery(request):
    users=Image1.objects.all()
    return render(request,'gallery.html',{'users':users})
    
def details(request,id):
    user=Image1.objects.get(id=id)
    return render(request,'details.html',{'user':user})


def update(request,id):
    updt=Signup1.objects.get(id=id)
    if request.method=='POST':
        form=UpdateForm(request.POST or None,instance=updt)
        if form.is_valid():
            form.save()
            messages.success(request, "Update Successfully")
            return redirect('/')
    else:
        form=UpdateForm(instance=updt)
    return render(request, 'update.html',{'updt':updt,'form':form})

def changepassword(request,id):
    delt=Signup1.objects.get(id=id)
    if request.method=='POST':
        form=ChangePasswordForm(request.POST)
        if form.is_valid():
            old=form.cleaned_data['OldPassword']
            new=form.cleaned_data['NewPassword']
            confirm=form.cleaned_data['ConfirmPassword']

            if old!=delt.Password:
                messages.warning(request, "Incorrect Password")
                return redirect('/changepassword/%s' % delt.id)
            elif old==new:
                messages.warning(request, "Same Password")
                return redirect('/changepassword/%s' % delt.id)
            elif new!=confirm:
                messages.warning(request,"Mismatch")
                return redirect('/changepassword/%s' % delt.id)
            else:
                delt.Password=new
                delt.save()
                messages.success(request, "Password Changed")
                return redirect('/home/%s' % delt.id)
    else:
        form=ChangePasswordForm()
    return render(request,'password.html',{'delt':delt,'form':form})


def logouts(request):
    logout(request)
    messages.success(request,"Logout Successfully")
    return redirect('/')

app1/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
<title>Garden Truck</title>
<meta charset="utf-8">
<link rel="icon" href="{% static 'images/favicon.ico' %}">
<link rel="shortcut icon" href="{% static 'images/favicon.ico' %}">
<link rel="stylesheet" href="{% static 'css/style.css' %}">
<link rel="stylesheet" href="{% static 'css/slider.css' %}">
<script src="{% static 'js/jquery.js' %}"></script>
<script src="{% static 'js/jquery-migrate-1.1.1.js' %}"></script>
<script src="{% static 'js/superfish.js' %}"></script>
<script src="{% static 'js/sForm.js' %}"></script>
<script src="{% static 'js/jquery.equalheights.js' %}"></script>
<script src="{% static 'js/jquery.easing.1.3.js' %}"></script>
<script src="{% static 'js/tms-0.4.1.js' %}"></script>
<script src="{% static 'js/jquery.carouFredSel-6.1.0-packed.js' %}"></script>
<script	src="{% static 'js/jquery.touchSwipe.min.js' %}"></script>
<script>
$(window).load(function () {
    $('.slider')._TMS({
        show: 0,
        pauseOnHover: false,
        prevBu: '.prev',
        nextBu: '.next',
        playBu: false,
        duration: 800,
        preset: 'fade',
        pagination: false, //'.pagination',true,'<ul></ul>'
        pagNums: false,
        slideshow: 8000,
        numStatus: false,
        banners: true,
        waitBannerAnimation: false,
        progressBar: false
    })
});
$(window).load(
    function () {
        $('.carousel1').carouFredSel({
            auto: false,
            prev: '.prev1',
            next: '.next1',
            width: 1030,
            items: {
                visible: {
                    min: 1,
                    max: 4
                },
                height: 'auto',
                width: 157,
            },
            responsive: true,
            scroll: 1,
            mousewheel: false,
            swipe: {
                onMouse: true,
                onTouch: true
            }
        });
    });
</script>
<!--[if lt IE 9]>
<script src="js/html5shiv.js"></script>
<link rel="stylesheet" media="screen" href="css/ie.css">
<![endif]-->
</head>
<body class="page1">
<header>
  <div class="container_12">
    <div class="grid_12">
      <div class="h_phone">Need Help? Call Us +1 (800) 123 4567</div>
      <h1><a href="index.html"><img src="{% static 'images/logo.png' %}" alt=""></a></h1>
      <div class="clear"></div>
    </div>
    <div class="clear"></div>
  </div>
  <div class="menu_block">
    <div class="container_12">
      <div class="grid_12">
        <div class="socials"><a href="#"></a><a href="#"></a></div>
        <div class="autor"> <a href="{% url 'app1:login' %}">User Login</a><a href="{% url 'app1:signup' %}">Signup</a><a href="{% url 'app1:gallery' %}">Gallery</a></div>
        <nav class="">
          <ul class="sf-menu">
            <li class="current"><a href="index.html">Home</a></li>
            <li class="with_ul"><a href="about.html">About</a></li>
            <li><a href="services.html">Services</a>
              <ul>
                <li><a href="#"> Services List</a>
                  <ul>
                    <li><a href="#">Seeds</a></li>
                    <li><a href="#">Traits</a></li>
                    <li><a href="#">Safety Control</a></li>
                  </ul>
                </li>
                <li><a href="#">Overview</a></li>
                <li><a href="#">FAQS</a></li>
              </ul>
            </li>
            <li><a href="products.html">Products</a></li>
            <li><a href="blog.html">Blog</a></li>
            <li><a href="contacts.html">Contacts</a></li>
          </ul>
        </nav>
        <div class="clear"></div>
      </div>
      <div class="clear"></div>
    </div>
  </div>
</header>

{% block content %}

{% endblock %}

<footer>
  <div class="container_12">
    <div class="grid_2">
      <div class="copy"> <a href="index.html" class="footer_logo"><img src="{% static 'images/footer_logo.png' %}"	alt=""></a> &copy; 2045 <a href="#">Privacy Policy</a> </div>
    </div>
    <div class="grid_2">
      <ul>
        <li><a href="#">Contact</a></li>
        <li><a href="#">Delivery</a></li>
        <li><a href="#">Legal Notice</a></li>
        <li><a href="#">Terms and Conditions</a></li>
        <li><a href="#">About Us</a></li>
      </ul>
    </div>
    <div class="grid_2">
      <ul>
        <li><a href="#">New Products</a></li>
        <li><a href="#">Top Sellers</a></li>
        <li><a href="#">Specials</a></li>
        <li><a href="#">Manufacturers</a></li>
        <li><a href="#">Suppliers</a></li>
      </ul>
    </div>
    <div class="grid_2">
      <ul>
        <li><a href="#">Science &amp; Safety</a></li>
        <li><a href="#">Product </a></li>
        <li><a href="#">Our Brands</a></li>
        <li><a href="#">Agricultural </a></li>
        <li><a href="#">Traits &amp; Technologies</a></li>
      </ul>
    </div>
    <div class="grid_3 prefix_1">
      <h4>Newsletter</h4>
      <form id="newsletter" action="#">
        <div class="success">Your subscribe request has been sent!</div>
        <label class="email"> <span>Enter e-mail address</span>
          <input type="email" value="" >
          <a href="#" class="btn" data-type="submit">Subscribe</a> <span class="error">*This is not a valid email address.</span> </label>
      </form>
    </div>
    <div class="clear"></div>
  </div>
  <div class="f_bot">
    <div class="container_12">
      <div class="grid_12">Design by: <a href="http://www.templatemonster.com/">TemplateMonster.com</a></div>
    </div>
  </div>
</footer>
</body>
</html>

app1/templates/details.html
<!DOCTYPE html>
    {% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% for msg in meassages %}
    {{msg}}
    {% endfor %}
<table>
    <tr>
        <th>DETAILS</th>
        <th>PHOTO</th>
    </tr>
    <tr>
        <td>{{user.id}} <br>
        {{user.Name}} <br>
        {{user.Brand}} <br>
        {{user.Model}} <br>
        {{user.year}}</td>
        <td><img src="{{user.Photo.url}}" alt="" height="120px" width="150px"></td>
    </tr>   
</table>
</body>
</html>

app1/templates/gallery.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<head>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <title>Document</title>
    
</head>
<body bgcolor="black">
    {% for msg in meassages %}
    {{msg}}
    {% endfor %}
    <div class="container">
        {% for user in users %}
        
        <div class="col-md-4">
                <a href="{% url 'app1:details' user.id %}"><img src="{{user.Photo.url}}" alt="" style="height:320px ;width: 400px;">
                <br>
                {{user.Name}}
                <br>
                </a>
        </div>
    
        {% endfor %} 
    </div>       
</body>
{% endblock %}

app1/templates/home.html
<!DOCTYPE html>
    {% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% for msg in meassages %}
    {{msg}}
    {% endfor %}
<div>
    <table>
        <tr>
            <th></th>
            <th></th>
        </tr>
        <tr>
            <td>{{data.Name}} <br><br>
                {{data.Age}} <br><br>
            </td>
            <td>
            <img src="{{data.Photo.url}}" alt="" height="200px" width="250px">
        </td>
        </tr>
    </table>
        <a href="{% url 'app1:update' data.id %}">Update</a>&nbsp;&nbsp;<a href="{% url 'app1:changepassword' data.id %}">Change Password</a>
        <br>
        <a href="{% url 'app1:logouts' %}">Logout</a>
</div>
</body>
</html>

app1/templates/image.html
<!DOCTYPE html>
<html lang="en">
    {% load static %}
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% for msg in messages %}
    {{msg}}
    {% endfor %}
    <br><br>
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <table>
            <tr>
            {{form.as_table}}
            </tr>
        </table>
        
        <input type="submit" value="Upload">
    </form>  
</body>
</html>

app1/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="slider-relative">
    <div class="slider-block">
      <div class="slider"> <a href="#" class="prev"></a> <a href="#" class="next"></a>
        <ul class="items">
          <li> <img src="{% static 'images/slide.jpg' %}" alt="">
            <div class="banner">Healthy life <br>
              <br>
              tastes delicious</div>
          </li>
          <li> <img src="{% static 'images/slide1.jpg' %}" alt="">
            <div class="banner">A new generation <br>
              <br>
              of farming</div>
          </li>
          <li> <img src="{% static 'images/slide2.jpg' %}" alt="">
            <div class="banner">Best food is<br>
              <br>
              natural food</div>
          </li>
          <li> <img src="{% static 'images/slide3.jpg' %}" alt="">
            <div class="banner">New agricultural <br>
              <br>
              technologies only</div>
          </li>
        </ul>
      </div>
    </div>
  </div>
  <div class="content">
    <div class="black">
      <div class="page1_block">
        <div class="container_12">
          <div class="grid_12">
            <h2>Natural and fresh goods only!<br>
              <br>
              <br>
              The best agricultural technologies</h2>
          </div>
          <div class="clear"></div>
        </div>
      </div>
      <div class="container_12">
        <div class="grid_3">
          <h3>Harvest</h3>
          <div class="col1">Qhasellus id adipiscing nunc. Tonec velko augue et nula ehicula pretium. Yonecjol po consequat achoumsan erat ac vulputatwyt. Ut consectetur commodo mollis. Ut necrcilo fg tells interdum aliquete. Phasellus juihers daiprtyiscing nunc. Conec vel augue etjotr lnulla hylo vehicula pretium. Nonec consde equat gtmk accumsan erat ac vulptase.</div>
          <a href="#" class="btn">More</a> </div>
        <div class="grid_3">
          <h3>Cultivation</h3>
          <div class="col1">Qhasellus id adipiscing nunc. Tonec velko augue et nula ehicula pretium. Yonecjol po consequat achoumsan erat ac vulputatwyt. Ut consectetur commodo mollis. Ut necrcilo fg tells interdum aliquete. Phasellus juihers daiprtyiscing nunc. Conec vel augue etjotr lnulla hylo vehicula pretium. Nonec consde equat gtmk accumsan erat ac vulptase.</div>
          <a href="#" class="btn">More</a> </div>
        <div class="grid_3">
          <h3>Protection</h3>
          <div class="col1">Qhasellus id adipiscing nunc. Tonec velko augue et nula ehicula pretium. Yonecjol po consequat achoumsan erat ac vulputatwyt. Ut consectetur commodo mollis. Ut necrcilo fg tells interdum aliquete. Phasellus juihers daiprtyiscing nunc. Conec vel augue etjotr lnulla hylo vehicula pretium. Nonec consde equat gtmk accumsan erat ac vulptase.</div>
          <a href="#" class="btn">More</a> </div>
        <div class="grid_3">
          <h3>Treatment</h3>
          <div class="col1">Qhasellus id adipiscing nunc. Tonec velko augue et nula ehicula pretium. Yonecjol po consequat achoumsan erat ac vulputatwyt. Ut consectetur commodo mollis. Ut necrcilo fg tells interdum aliquete. Phasellus juihers daiprtyiscing nunc. Conec vel augue etjotr lnulla hylo vehicula pretium. Nonec consde equat gtmk accumsan erat ac vulptase.</div>
          <a href="#" class="btn">More</a> </div>
        <div class="clear"></div>
      </div>
    </div>
    <div class="white">
      <div class="container_12">
        <div class="grid_7">
          <h3>Company Products</h3>
          <img src="{% static 'images/page1_img1.jpg' %}" alt="" class="img_inner fleft">
          <div class="extra_wrapper">
            <div class="text1"> Aliquam placerat ligula eu sem facilj is semper porta sem pellentesque. </div>
            <p class="col1"><a class="col2" href="#">Click here</a> for more info about this free website template created by TemplateMonster.com </p>
            Lkhasellus id adipiscing nunc. Donecvelqq wr augue et nulla vehicula pretium. Donew ctryi weconsequat accumsan erat ac vu jo lputate. Kt consectetur commodo mollis. Ut necrci we tellus interdum aliquet. Johaseko kolo	lus id adipiscing nunc. Donec veldsak augue et nulr jver ehicula pretium. <br>
            <a href="#" class="btn">More</a> </div>
        </div>
        <div class="grid_4 prefix_1">
          <h3>Technologies</h3>
          <img src="{% static 'images/page1_img2.jpg' %}" alt="" class="img_inner fleft i1">
          <div class="extra_wrapper">
            <div class="col1"> <a href="#">Mklhasellus aed hadipiscin nury.</a> </div>
            Konecvel whjugute etew nulla vehiculuote. pretium. Donew ctryi weconsequat accure msan erat ac vu jo lputatesectetur. </div>
          <div class="clear cl1"></div>
          <img src="{% static 'images/page1_img3.jpg' %}" alt="" class="img_inner fleft i1">
          <div class="extra_wrapper">
            <div class="col1"> <a href="#">Uokhasellus id adipiscing nu.</a> </div>
            Honecvelqq whjugue et nulla vehiculuowe. Kjonecvelqq jugue et nulla vehiculoretium. Donew ctryi weconsequat accumsan. </div>
          <div class="clear cl2"></div>
          <img src="{% static 'images/page1_img4.jpg' %}" alt="" class="img_inner fleft i1">
          <div class="extra_wrapper">
            <div class="col1 "> <a href="#">Lkokhasellusuop adipiscing nuretilo kolitri.</a> </div>
            Kjonecvelqq jugue et nulla vehiculoretium. Donew ctryi weconsequat accumsan erat ac vu jo lputateconsectetur commodo. </div>
          <div class="clear"></div>
          <a href="#" class="btn">More</a> </div>
        <div class="clear"></div>
      </div>
    </div>
    <div class="gray">
      <div class="container_12">
        <div class="grid_12">
          <div class="car"> <a href="#" class="prev1"></a> <a href="#" class="next1"></a>
            <div class="car_div">
              <ul class="carousel1">
                <li><a href="#"><img src="{% static 'images/logo1.png' %}" alt=""></a></li>
                <li><a href="#"><img src="{% static 'images/logo2.png' %}" alt=""></a></li>
                <li><a href="#"><img src="{% static 'images/logo3.png' %}" alt=""></a></li>
                <li><a href="#"><img src="{% static 'images/logo4.png' %}" alt=""></a></li>
                <li><a href="#"><img src="{% static 'images/logo2.png' %}" alt=""></a></li>
              </ul>
            </div>
          </div>
        </div>
        <div class="clear"></div>
      </div>
    </div>
  </div>
  
{% endblock%}

app1/templates/login.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    {% for msg in meassages %}
    {{msg}}
    {% endfor %}
    <br><br>
    <h2 style="text-align:center ;"><b>
        <i>LOGIN</i>
    </b></h2>
    <br><br>
    <form action="" method="post" style="align-content:center ;">   
         {% csrf_token %}
    <table style="align-items:center ;">
        <tr>
            {{form.as_table}}
        </tr>
    </table>
    <input type="submit" value="LOGIN">
    <br><br><br>

    
</form>
<a href="{% url 'app1:signup' %}">Create Account</a> 
{% endblock %}

app1/templates/password.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% for msg in meassages %}
    {{msg}}
    {% endfor %}
    <br><br>
    <form action="" method="post">   
         {% csrf_token %}
    <table>
        <tr>
            {{form.as_table}}
        </tr>
    </table>
    <input type="submit" value="Update">   
</form>
</body>
</html>

app1/templates/signup.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<body style="text-align:center ;">
    {% for msg in meassages %}
    {{msg}}
    {% endfor %}
    <br><br>
    <h2 style="text-align:center ;"><b><i>SIGNUP</i></b></h2>
    <br><br>
    <div style="text-align:center ;">
    <form action="" method="post" enctype="multipart/form-data">   
         {% csrf_token %}
    <table>
        <tr>
            {{form.as_table}}
            
        </tr>
    </table>
    <input type="submit" value="submit">
</form>
</div>
{% endblock %}

app1/templates/update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% for msg in meassages %}
    {{msg}}
    {% endfor %}
    <form action="" method="post">
        {% csrf_token %}
        <table>
            <tr>
                {{form.as_table}}
            </tr>
        </table>
        <input type="submit" value="Update">
    </form>
</body>
</html>